# Generated by Django 5.1 on 2024-09-01 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
