# Generated by Django 5.1 on 2024-09-01 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_checkout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
