# Generated by Django 5.1 on 2024-09-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_checkout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100, verbose_name='First Name')),
                ('lname', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.CharField(max_length=100, verbose_name='Email Address')),
                ('message', models.CharField(max_length=100, verbose_name='Message')),
            ],
        ),
    ]
